export const movies = [{
    "id": 1,
    "title": "Ratatouille",
    "year": 2007,
    "rated": "G",
    "genre": "Family, Comedy",
    "plot": "The rat can cook! This sweetly ridiculous movie about a naive, ambitious rodent named Remy (charmingly voiced by Patton Oswalt), who longs to become a great chef is witty, clever, gently moral and dramatically convincing. Who doesn't love Linguini (voiced by Lou Romano), a hopeless human moppet controlled by the supremely talented Remy? Will they win over the Snow White-style villain, a power-crazed food critic named Anton Ego (Peter O'Toole)?",
    "poster": "https://d2e111jq13me73.cloudfront.net/sites/default/files/styles/product_image_aspect_switcher_170w/public/product-images/csm-movie/ratatouille-resized-opt.jpg?itok=iDHf7hcU",
  },
  {
    "id": 2,
    "title": "Beauty and the Beast",
    "year": 1991,
    "rated": "G",
    "genre": "Musical, Fantasy",
    "plot": "A pompous prince gets a taste of his own medicine in this '90s fairytale. An enchantress' spell turns the royal into a ferocious beast, and it cannot be undone until he falls in love. When the beast kidnaps the town's clockmaster, his beautiful daughter comes to the rescue...and the beast's, too.",
    "poster": "https://resizing.flixster.com/_sS5KRPtwLqzg4gGci9ZX02hmtY=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzL2Q1OWQzMzQ0LWY0YTgtNGI1ZS05NjRlLTk5NWMwMjVhYjQ0Yy53ZWJw",
  },
  {
    "id": 3,
    "title": "101 Dalmations",
    "year": 1961,
    "rated": "G",
    "genre": "Family, Adventure",
    "plot": "It's true love for Pongo and Perdita! Fortunately for the pups, they're able to wrangle their owners into a relationship, too. It's nothing but canine bliss...until the mean-spirited Cruella De Vil shows up. She has her sights set on Perdita's liter of pups...for fur coats.",
    "poster": "https://d2e111jq13me73.cloudfront.net/sites/default/files/styles/product_image_aspect_switcher_170w/public/product-images/csm-movie/101-dalmatians-poster.jpg?itok=MEc1Fd_8",
  },
  {
    "id": 4,
    "title": "Coco",
    "year": 2017,
    "rated": "PG",
    "genre": "Family, Adventure",
    "plot": "Ernesto de la Cruz—a fictional Sinatra, if you will—is Miguel's idol. All the youngster longs for is to belt out beautiful ballads like his favorite singer. However, music is strongly prohibited in his family, for reasons unknown. With a trip to the Land of the Dead, Miguel starts to make sense of his family's ways.",
    "poster": "https://d2e111jq13me73.cloudfront.net/sites/default/files/styles/product_image_aspect_switcher_170w/public/product-images/csm-movie/coco-resized-opt.jpg?itok=Ztite2fh",
  },
  {
    "id": 5,
    "title": "Zootopia",
    "year": 2016,
    "rated": "PG",
    "genre": "Family, Comedy",
    "plot": "Judy Hopps dreams of joining the police force and leaves her farm and family for the bustling metropolis Zootopia to achieve this goal. As the first rabbit in the crew, she isn’t taken seriously by her fellow police officers. Tired of writing up parking violations, Judy decides to take on a missing persons case to prove herself. When she enlists the unwilling help of con fox Nick Wilde, the pair find themselves going down a rabbit hole of clues, scandals and close calls.",
    "poster": "https://d2e111jq13me73.cloudfront.net/sites/default/files/styles/product_image_aspect_switcher_170w/public/product-images/csm-movie/zootopia-poster.jpg?itok=qEaOY5OM",
  },
  {
    "id": 6,
    "title": "Lady and the Tramp",
    "year": 1955,
    "rated": "G",
    "genre": "Family, Romance",
    "plot": "A sophisticated cocker spaniel and a pup from the wrong side of the tracks fall in love in this pawsitively irresistible canine romance. Generations later, we'll still swoon for the classic spaghetti-slurping scene between the two doggos.",
    "poster": "https://flxt.tmsimg.com/assets/p10675_p_v10_af.jpg",
  },
  {
    "id": 7,
    "title": "Lady and the Tramp",
    "year": 2019,
    "rated": "PG",
    "genre": "Family, Romance",
    "plot": "This live-action update of the classic brings a realistic edge to the comedy–and drama–of the ultimate canine meet-cute. And yes, the spaghetti scene is here in all its slurp-tastic glory.",
    "poster": "https://m.media-amazon.com/images/M/MV5BM2U3ZDBkYWUtNDY3Ny00OTliLTgxNTAtY2QwZTQxMmEwOTQ1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  },
  {
    "id": 8,
    "title": "Snow White and the Seven Dwarves",
    "year": 1937,
    "rated": "G",
    "genre": "Family, Fantasy",
    "plot": "Talk about jealousy at its finest. A wicked queen simply cannot stand her young stepdaughter's beauty and even goes so far as to take the life of young Snow White. But the joke's on the bitter royal, as Snow White emerges alive and well, enjoying the company of seven dwarves in a cozy cottage. That's when the queen tries again. She disguises herself as an old lady and offers Snow White a poisonous apple that sends her into a unconscious state that can only be broken with the kiss of a prince.",
    "poster": "https://static.rogerebert.com/uploads/movie/movie_poster/snow-white-and-the-seven-dwarfs-1937/large_vB1p70FfFMxNB0X6hub662kHj71.jpg",
  },
  {
    "id": 9,
    "title": "The Lion King",
    "year": 1994,
    "rated": "G",
    "genre": "Family, Musical",
    "plot": "Equal parts endearing and heartbreaking, the Disney classic rotates around young lion Simba, who must rise to power after the loss of his father, Mufasa. You would think family would be supportive, but one evil uncle has it in for the cub. Hang in there, Simba! Remember: Hakuna matata!",
    "poster": "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg",
  },
  {
    "id": 10,
    "title": "The Lion King",
    "year": 2019,
    "rated": "PG",
    "genre": "Family, Adventure",
    "plot": "This photorealistic film is a study piece of Hamlet-derived musical theater, only with 100 percent more Beyoncé, which is never a bad thing. Set in one of Africa’s most beautiful valleys, today’s Lion King remains a story about talking and singing animals that connect with the tides of the earth—and that create conflict with each other. It's not only more realistic than the original, it's darker and more dramatic. ",
    "poster": "https://images.moviesanywhere.com/c07276e9473360730fdbc94baebc4236/4692c964-61ba-486d-9c77-939dbfba2f07.jpg",
  },
  {
    "id": 11,
    "title": "The Hunchback of Notre Dame",
    "year": 1996,
    "rated": "G",
    "genre": "Family, Musical",
    "plot": "This adaptation of Victor Hugo's classic novel Notre Dame de Paris stars Quasimodo (voiced by Tom Hulce), a grotesquely deformed but kind-hearted young man who was abandoned by his parents and rescued by the priests of Notre Dame, the massive cathedral in the heart of Paris, and he lives there, earning his keep as a bell ringer. Quasimodo has become the ward of Judge Frollo (voiced by Tony Jay), an outwardly pious but deeply hateful man.",
    "poster": "https://bestsimilar.com/img/movie/thumb/2f/15446.jpg",
  },
  {
    "id": 12,
    "title": "Mulan",
    "year": 1998,
    "rated": "G",
    "genre": "Family, Musical",
    "plot": "Mulan doesn't let anything stand in her way. She's fearful that her ailing father will be forced to serve in the military. That's when she gets the idea to go undercover as a man—a highly forbidden act. In true Disney fashion, there's also some romance along the way.",
    "poster": "https://bestsimilar.com/img/movie/thumb/06/18789.jpg",
  }
]